// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "gift_manager/internal/models"
)

// EventPublisher is an autogenerated mock type for the EventPublisher type
type EventPublisher struct {
	mock.Mock
}

type EventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *EventPublisher) EXPECT() *EventPublisher_Expecter {
	return &EventPublisher_Expecter{mock: &_m.Mock}
}

// PublishPersonEvent provides a mock function with given fields: ctx, event
func (_m *EventPublisher) PublishPersonEvent(ctx context.Context, event *models.PersonEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishPersonEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.PersonEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventPublisher_PublishPersonEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishPersonEvent'
type EventPublisher_PublishPersonEvent_Call struct {
	*mock.Call
}

// PublishPersonEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - event *models.PersonEvent
func (_e *EventPublisher_Expecter) PublishPersonEvent(ctx interface{}, event interface{}) *EventPublisher_PublishPersonEvent_Call {
	return &EventPublisher_PublishPersonEvent_Call{Call: _e.mock.On("PublishPersonEvent", ctx, event)}
}

func (_c *EventPublisher_PublishPersonEvent_Call) Run(run func(ctx context.Context, event *models.PersonEvent)) *EventPublisher_PublishPersonEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.PersonEvent))
	})
	return _c
}

func (_c *EventPublisher_PublishPersonEvent_Call) Return(_a0 error) *EventPublisher_PublishPersonEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventPublisher_PublishPersonEvent_Call) RunAndReturn(run func(context.Context, *models.PersonEvent) error) *EventPublisher_PublishPersonEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventPublisher creates a new instance of EventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventPublisher {
	mock := &EventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
