// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "gift_manager/internal/models"
)

// GiftHistoryRepository is an autogenerated mock type for the GiftHistoryRepository type
type GiftHistoryRepository struct {
	mock.Mock
}

type GiftHistoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *GiftHistoryRepository) EXPECT() *GiftHistoryRepository_Expecter {
	return &GiftHistoryRepository_Expecter{mock: &_m.Mock}
}

// AddGiftHistory provides a mock function with given fields: ctx, history
func (_m *GiftHistoryRepository) AddGiftHistory(ctx context.Context, history *models.GiftHistory) error {
	ret := _m.Called(ctx, history)

	if len(ret) == 0 {
		panic("no return value specified for AddGiftHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.GiftHistory) error); ok {
		r0 = rf(ctx, history)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GiftHistoryRepository_AddGiftHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddGiftHistory'
type GiftHistoryRepository_AddGiftHistory_Call struct {
	*mock.Call
}

// AddGiftHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - history *models.GiftHistory
func (_e *GiftHistoryRepository_Expecter) AddGiftHistory(ctx interface{}, history interface{}) *GiftHistoryRepository_AddGiftHistory_Call {
	return &GiftHistoryRepository_AddGiftHistory_Call{Call: _e.mock.On("AddGiftHistory", ctx, history)}
}

func (_c *GiftHistoryRepository_AddGiftHistory_Call) Run(run func(ctx context.Context, history *models.GiftHistory)) *GiftHistoryRepository_AddGiftHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.GiftHistory))
	})
	return _c
}

func (_c *GiftHistoryRepository_AddGiftHistory_Call) Return(_a0 error) *GiftHistoryRepository_AddGiftHistory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GiftHistoryRepository_AddGiftHistory_Call) RunAndReturn(run func(context.Context, *models.GiftHistory) error) *GiftHistoryRepository_AddGiftHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetGiftHistoryByPersonID provides a mock function with given fields: ctx, personID
func (_m *GiftHistoryRepository) GetGiftHistoryByPersonID(ctx context.Context, personID int64) ([]*models.GiftHistory, error) {
	ret := _m.Called(ctx, personID)

	if len(ret) == 0 {
		panic("no return value specified for GetGiftHistoryByPersonID")
	}

	var r0 []*models.GiftHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*models.GiftHistory, error)); ok {
		return rf(ctx, personID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*models.GiftHistory); ok {
		r0 = rf(ctx, personID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.GiftHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, personID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GiftHistoryRepository_GetGiftHistoryByPersonID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGiftHistoryByPersonID'
type GiftHistoryRepository_GetGiftHistoryByPersonID_Call struct {
	*mock.Call
}

// GetGiftHistoryByPersonID is a helper method to define mock.On call
//   - ctx context.Context
//   - personID int64
func (_e *GiftHistoryRepository_Expecter) GetGiftHistoryByPersonID(ctx interface{}, personID interface{}) *GiftHistoryRepository_GetGiftHistoryByPersonID_Call {
	return &GiftHistoryRepository_GetGiftHistoryByPersonID_Call{Call: _e.mock.On("GetGiftHistoryByPersonID", ctx, personID)}
}

func (_c *GiftHistoryRepository_GetGiftHistoryByPersonID_Call) Run(run func(ctx context.Context, personID int64)) *GiftHistoryRepository_GetGiftHistoryByPersonID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *GiftHistoryRepository_GetGiftHistoryByPersonID_Call) Return(_a0 []*models.GiftHistory, _a1 error) *GiftHistoryRepository_GetGiftHistoryByPersonID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GiftHistoryRepository_GetGiftHistoryByPersonID_Call) RunAndReturn(run func(context.Context, int64) ([]*models.GiftHistory, error)) *GiftHistoryRepository_GetGiftHistoryByPersonID_Call {
	_c.Call.Return(run)
	return _c
}

// NewGiftHistoryRepository creates a new instance of GiftHistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGiftHistoryRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GiftHistoryRepository {
	mock := &GiftHistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
