// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "gift_manager/internal/models"
)

// GiftIdeaRepository is an autogenerated mock type for the GiftIdeaRepository type
type GiftIdeaRepository struct {
	mock.Mock
}

type GiftIdeaRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *GiftIdeaRepository) EXPECT() *GiftIdeaRepository_Expecter {
	return &GiftIdeaRepository_Expecter{mock: &_m.Mock}
}

// AddGiftIdea provides a mock function with given fields: ctx, idea
func (_m *GiftIdeaRepository) AddGiftIdea(ctx context.Context, idea *models.GiftIdea) error {
	ret := _m.Called(ctx, idea)

	if len(ret) == 0 {
		panic("no return value specified for AddGiftIdea")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.GiftIdea) error); ok {
		r0 = rf(ctx, idea)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GiftIdeaRepository_AddGiftIdea_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddGiftIdea'
type GiftIdeaRepository_AddGiftIdea_Call struct {
	*mock.Call
}

// AddGiftIdea is a helper method to define mock.On call
//   - ctx context.Context
//   - idea *models.GiftIdea
func (_e *GiftIdeaRepository_Expecter) AddGiftIdea(ctx interface{}, idea interface{}) *GiftIdeaRepository_AddGiftIdea_Call {
	return &GiftIdeaRepository_AddGiftIdea_Call{Call: _e.mock.On("AddGiftIdea", ctx, idea)}
}

func (_c *GiftIdeaRepository_AddGiftIdea_Call) Run(run func(ctx context.Context, idea *models.GiftIdea)) *GiftIdeaRepository_AddGiftIdea_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.GiftIdea))
	})
	return _c
}

func (_c *GiftIdeaRepository_AddGiftIdea_Call) Return(_a0 error) *GiftIdeaRepository_AddGiftIdea_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GiftIdeaRepository_AddGiftIdea_Call) RunAndReturn(run func(context.Context, *models.GiftIdea) error) *GiftIdeaRepository_AddGiftIdea_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGiftIdea provides a mock function with given fields: ctx, personID, ideaID
func (_m *GiftIdeaRepository) DeleteGiftIdea(ctx context.Context, personID int64, ideaID int64) error {
	ret := _m.Called(ctx, personID, ideaID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGiftIdea")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, personID, ideaID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GiftIdeaRepository_DeleteGiftIdea_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGiftIdea'
type GiftIdeaRepository_DeleteGiftIdea_Call struct {
	*mock.Call
}

// DeleteGiftIdea is a helper method to define mock.On call
//   - ctx context.Context
//   - personID int64
//   - ideaID int64
func (_e *GiftIdeaRepository_Expecter) DeleteGiftIdea(ctx interface{}, personID interface{}, ideaID interface{}) *GiftIdeaRepository_DeleteGiftIdea_Call {
	return &GiftIdeaRepository_DeleteGiftIdea_Call{Call: _e.mock.On("DeleteGiftIdea", ctx, personID, ideaID)}
}

func (_c *GiftIdeaRepository_DeleteGiftIdea_Call) Run(run func(ctx context.Context, personID int64, ideaID int64)) *GiftIdeaRepository_DeleteGiftIdea_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *GiftIdeaRepository_DeleteGiftIdea_Call) Return(_a0 error) *GiftIdeaRepository_DeleteGiftIdea_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GiftIdeaRepository_DeleteGiftIdea_Call) RunAndReturn(run func(context.Context, int64, int64) error) *GiftIdeaRepository_DeleteGiftIdea_Call {
	_c.Call.Return(run)
	return _c
}

// GetGiftIdeasByPersonID provides a mock function with given fields: ctx, personID
func (_m *GiftIdeaRepository) GetGiftIdeasByPersonID(ctx context.Context, personID int64) ([]*models.GiftIdea, error) {
	ret := _m.Called(ctx, personID)

	if len(ret) == 0 {
		panic("no return value specified for GetGiftIdeasByPersonID")
	}

	var r0 []*models.GiftIdea
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*models.GiftIdea, error)); ok {
		return rf(ctx, personID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*models.GiftIdea); ok {
		r0 = rf(ctx, personID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.GiftIdea)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, personID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GiftIdeaRepository_GetGiftIdeasByPersonID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGiftIdeasByPersonID'
type GiftIdeaRepository_GetGiftIdeasByPersonID_Call struct {
	*mock.Call
}

// GetGiftIdeasByPersonID is a helper method to define mock.On call
//   - ctx context.Context
//   - personID int64
func (_e *GiftIdeaRepository_Expecter) GetGiftIdeasByPersonID(ctx interface{}, personID interface{}) *GiftIdeaRepository_GetGiftIdeasByPersonID_Call {
	return &GiftIdeaRepository_GetGiftIdeasByPersonID_Call{Call: _e.mock.On("GetGiftIdeasByPersonID", ctx, personID)}
}

func (_c *GiftIdeaRepository_GetGiftIdeasByPersonID_Call) Run(run func(ctx context.Context, personID int64)) *GiftIdeaRepository_GetGiftIdeasByPersonID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *GiftIdeaRepository_GetGiftIdeasByPersonID_Call) Return(_a0 []*models.GiftIdea, _a1 error) *GiftIdeaRepository_GetGiftIdeasByPersonID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GiftIdeaRepository_GetGiftIdeasByPersonID_Call) RunAndReturn(run func(context.Context, int64) ([]*models.GiftIdea, error)) *GiftIdeaRepository_GetGiftIdeasByPersonID_Call {
	_c.Call.Return(run)
	return _c
}

// NewGiftIdeaRepository creates a new instance of GiftIdeaRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGiftIdeaRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GiftIdeaRepository {
	mock := &GiftIdeaRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
