// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "gift_manager/internal/models"
)

// PersonRepository is an autogenerated mock type for the PersonRepository type
type PersonRepository struct {
	mock.Mock
}

type PersonRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *PersonRepository) EXPECT() *PersonRepository_Expecter {
	return &PersonRepository_Expecter{mock: &_m.Mock}
}

// AddPerson provides a mock function with given fields: ctx, person
func (_m *PersonRepository) AddPerson(ctx context.Context, person *models.Person) (int64, error) {
	ret := _m.Called(ctx, person)

	if len(ret) == 0 {
		panic("no return value specified for AddPerson")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Person) (int64, error)); ok {
		return rf(ctx, person)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Person) int64); ok {
		r0 = rf(ctx, person)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Person) error); ok {
		r1 = rf(ctx, person)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PersonRepository_AddPerson_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPerson'
type PersonRepository_AddPerson_Call struct {
	*mock.Call
}

// AddPerson is a helper method to define mock.On call
//   - ctx context.Context
//   - person *models.Person
func (_e *PersonRepository_Expecter) AddPerson(ctx interface{}, person interface{}) *PersonRepository_AddPerson_Call {
	return &PersonRepository_AddPerson_Call{Call: _e.mock.On("AddPerson", ctx, person)}
}

func (_c *PersonRepository_AddPerson_Call) Run(run func(ctx context.Context, person *models.Person)) *PersonRepository_AddPerson_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Person))
	})
	return _c
}

func (_c *PersonRepository_AddPerson_Call) Return(_a0 int64, _a1 error) *PersonRepository_AddPerson_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PersonRepository_AddPerson_Call) RunAndReturn(run func(context.Context, *models.Person) (int64, error)) *PersonRepository_AddPerson_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePerson provides a mock function with given fields: ctx, id
func (_m *PersonRepository) DeletePerson(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePerson")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PersonRepository_DeletePerson_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePerson'
type PersonRepository_DeletePerson_Call struct {
	*mock.Call
}

// DeletePerson is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *PersonRepository_Expecter) DeletePerson(ctx interface{}, id interface{}) *PersonRepository_DeletePerson_Call {
	return &PersonRepository_DeletePerson_Call{Call: _e.mock.On("DeletePerson", ctx, id)}
}

func (_c *PersonRepository_DeletePerson_Call) Run(run func(ctx context.Context, id int64)) *PersonRepository_DeletePerson_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PersonRepository_DeletePerson_Call) Return(_a0 error) *PersonRepository_DeletePerson_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PersonRepository_DeletePerson_Call) RunAndReturn(run func(context.Context, int64) error) *PersonRepository_DeletePerson_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllPersons provides a mock function with given fields: ctx
func (_m *PersonRepository) GetAllPersons(ctx context.Context) ([]*models.Person, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPersons")
	}

	var r0 []*models.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Person, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Person); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PersonRepository_GetAllPersons_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPersons'
type PersonRepository_GetAllPersons_Call struct {
	*mock.Call
}

// GetAllPersons is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PersonRepository_Expecter) GetAllPersons(ctx interface{}) *PersonRepository_GetAllPersons_Call {
	return &PersonRepository_GetAllPersons_Call{Call: _e.mock.On("GetAllPersons", ctx)}
}

func (_c *PersonRepository_GetAllPersons_Call) Run(run func(ctx context.Context)) *PersonRepository_GetAllPersons_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PersonRepository_GetAllPersons_Call) Return(_a0 []*models.Person, _a1 error) *PersonRepository_GetAllPersons_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PersonRepository_GetAllPersons_Call) RunAndReturn(run func(context.Context) ([]*models.Person, error)) *PersonRepository_GetAllPersons_Call {
	_c.Call.Return(run)
	return _c
}

// GetPersonByID provides a mock function with given fields: ctx, id
func (_m *PersonRepository) GetPersonByID(ctx context.Context, id int64) (*models.Person, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPersonByID")
	}

	var r0 *models.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.Person, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Person); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PersonRepository_GetPersonByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPersonByID'
type PersonRepository_GetPersonByID_Call struct {
	*mock.Call
}

// GetPersonByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *PersonRepository_Expecter) GetPersonByID(ctx interface{}, id interface{}) *PersonRepository_GetPersonByID_Call {
	return &PersonRepository_GetPersonByID_Call{Call: _e.mock.On("GetPersonByID", ctx, id)}
}

func (_c *PersonRepository_GetPersonByID_Call) Run(run func(ctx context.Context, id int64)) *PersonRepository_GetPersonByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *PersonRepository_GetPersonByID_Call) Return(_a0 *models.Person, _a1 error) *PersonRepository_GetPersonByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PersonRepository_GetPersonByID_Call) RunAndReturn(run func(context.Context, int64) (*models.Person, error)) *PersonRepository_GetPersonByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePerson provides a mock function with given fields: ctx, person
func (_m *PersonRepository) UpdatePerson(ctx context.Context, person *models.Person) error {
	ret := _m.Called(ctx, person)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePerson")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Person) error); ok {
		r0 = rf(ctx, person)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PersonRepository_UpdatePerson_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePerson'
type PersonRepository_UpdatePerson_Call struct {
	*mock.Call
}

// UpdatePerson is a helper method to define mock.On call
//   - ctx context.Context
//   - person *models.Person
func (_e *PersonRepository_Expecter) UpdatePerson(ctx interface{}, person interface{}) *PersonRepository_UpdatePerson_Call {
	return &PersonRepository_UpdatePerson_Call{Call: _e.mock.On("UpdatePerson", ctx, person)}
}

func (_c *PersonRepository_UpdatePerson_Call) Run(run func(ctx context.Context, person *models.Person)) *PersonRepository_UpdatePerson_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Person))
	})
	return _c
}

func (_c *PersonRepository_UpdatePerson_Call) Return(_a0 error) *PersonRepository_UpdatePerson_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PersonRepository_UpdatePerson_Call) RunAndReturn(run func(context.Context, *models.Person) error) *PersonRepository_UpdatePerson_Call {
	_c.Call.Return(run)
	return _c
}

// NewPersonRepository creates a new instance of PersonRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPersonRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PersonRepository {
	mock := &PersonRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
