// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "gift_manager/internal/models"
)

// ServiceInterface is an autogenerated mock type for the ServiceInterface type
type ServiceInterface struct {
	mock.Mock
}

type ServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceInterface) EXPECT() *ServiceInterface_Expecter {
	return &ServiceInterface_Expecter{mock: &_m.Mock}
}

// GetAllPersons provides a mock function with given fields: ctx
func (_m *ServiceInterface) GetAllPersons(ctx context.Context) ([]*models.Person, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPersons")
	}

	var r0 []*models.Person
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Person, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Person); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Person)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceInterface_GetAllPersons_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllPersons'
type ServiceInterface_GetAllPersons_Call struct {
	*mock.Call
}

// GetAllPersons is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ServiceInterface_Expecter) GetAllPersons(ctx interface{}) *ServiceInterface_GetAllPersons_Call {
	return &ServiceInterface_GetAllPersons_Call{Call: _e.mock.On("GetAllPersons", ctx)}
}

func (_c *ServiceInterface_GetAllPersons_Call) Run(run func(ctx context.Context)) *ServiceInterface_GetAllPersons_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ServiceInterface_GetAllPersons_Call) Return(_a0 []*models.Person, _a1 error) *ServiceInterface_GetAllPersons_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ServiceInterface_GetAllPersons_Call) RunAndReturn(run func(context.Context) ([]*models.Person, error)) *ServiceInterface_GetAllPersons_Call {
	_c.Call.Return(run)
	return _c
}

// SendPersonEvent provides a mock function with given fields: ctx, person, eventType
func (_m *ServiceInterface) SendPersonEvent(ctx context.Context, person *models.Person, eventType models.EventType) error {
	ret := _m.Called(ctx, person, eventType)

	if len(ret) == 0 {
		panic("no return value specified for SendPersonEvent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Person, models.EventType) error); ok {
		r0 = rf(ctx, person, eventType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceInterface_SendPersonEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPersonEvent'
type ServiceInterface_SendPersonEvent_Call struct {
	*mock.Call
}

// SendPersonEvent is a helper method to define mock.On call
//   - ctx context.Context
//   - person *models.Person
//   - eventType models.EventType
func (_e *ServiceInterface_Expecter) SendPersonEvent(ctx interface{}, person interface{}, eventType interface{}) *ServiceInterface_SendPersonEvent_Call {
	return &ServiceInterface_SendPersonEvent_Call{Call: _e.mock.On("SendPersonEvent", ctx, person, eventType)}
}

func (_c *ServiceInterface_SendPersonEvent_Call) Run(run func(ctx context.Context, person *models.Person, eventType models.EventType)) *ServiceInterface_SendPersonEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Person), args[2].(models.EventType))
	})
	return _c
}

func (_c *ServiceInterface_SendPersonEvent_Call) Return(_a0 error) *ServiceInterface_SendPersonEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServiceInterface_SendPersonEvent_Call) RunAndReturn(run func(context.Context, *models.Person, models.EventType) error) *ServiceInterface_SendPersonEvent_Call {
	_c.Call.Return(run)
	return _c
}

// NewServiceInterface creates a new instance of ServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceInterface {
	mock := &ServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
